baseurl = "http://bitcoin-class.org"
languageCode = "en-us"
title = "Cryptocurrency Cabal"
subtitle = "cs4501: Fall 2015"

GOOGLE_ANALYTICS = "UA-3775212-1"
DISQUS_SITENAME = "davidevans"

[params]
    sidebartitle = "Crypto Currency Cabal"
    sidebartagline = "University of Virginia"
    sidebartagline2 = "cs4501 Fall 2015"
    nodate = true
    noauthor = true
    noread = true
    nopaging=true
    notoc=true

[[menu.main]]


[[menu.footer]]

